export const emojiDataset = {
  avatarIdentity: [
    '🙂',
    '😄',
    '😃',
    '😊',
    '😌',
    '😐',
    '😶',
    '😮',
    '😯',
    '😲',
    '🧑',
    '👶',
    '🧒',
    '👦',
    '👧',
    '🧓',
    '👵',
    '👴',
    '🧑‍🦱',
    '🧑‍🦰',
    '🧑‍🦳',
    '🧑‍🦲',
    '🤝',
    '🫶',
    '🫂',
    '👋',
    '🙌',
    '🙏',
  ],
  emotions: {
    positiveHappy: [
      '😀',
      '😄',
      '😁',
      '😊',
      '😆',
      '🤩',
      '😍',
      '🥰',
      '😌',
      '😇',
      '🥳',
      '😎',
      '💖',
      '💕',
      '✨',
      '💫',
    ],
    neutralThinking: ['😐', '😑', '🤔', '🫠', '😶', '😬', '🙃'],
    sadComfort: ['😢', '😭', '😔', '😞', '😟', '😕', '🥺', '💔'],
    angryStress: ['😠', '😡', '🤬', '😤', '😾'],
    surprisedFear: ['😮', '😯', '😲', '😱', '😨'],
    tiredRest: ['😴', '🥱', '😪', '😌', '🛌'],
  },
  rooms: [
    '🌍',
    '💪',
    '👕',
    '🍜',
    '🌤️',
    '🎨',
    '🏫',
    '🐶',
    '🎵',
    '🎮',
    '✈️',
    '🏠',
  ],
  dailyActivitiesChallenges: [
    '💪',
    '🏃',
    '🧘',
    '🤸',
    '🚴',
    '🏋️',
    '👕',
    '👖',
    '👗',
    '👟',
    '🧢',
    '🎒',
    '🍚',
    '🍜',
    '🍣',
    '🍔',
    '🥗',
    '🍎',
    '☕',
    '🎨',
    '🎧',
    '🎮',
    '📸',
    '🎬',
    '🎶',
    '🌤️',
    '☀️',
    '🌧️',
    '🌈',
    '🌙',
    '⭐',
  ],
  emotionalSymbols: ['❤️', '💔', '💕', '💖'],
  energySymbols: ['🔥', '💯', '✨', '🌈'],
  thoughtSymbols: ['💭', '💬', '❗', '❓'],
  timeGoalSymbols: ['⏰', '📅', '🎯'],
  exampleExpressions: ['😴💭☕', '💪🔥💯', '😢🫶🌙'],
  socialCommunity: ['👋', '🤝', '🫶', '🫂', '💌', '📩', '📤', '🔔', '🎁', '⭐'],
  systemSafetyUiOnly: ['⚠️', '🚫', '❌', '✅', '☑️', '🔒', '🛡️', '🧩'],
} as const;

export const recommendedDefaultAvatars = ['🙂', '😊', '😄', '🫶'] as const;

export const mobileOptimizedSets = {
  avatarPicker: ['🙂', '😄', '😊', '😌', '😐', '😮', '🧑', '🧒', '🧓', '🧑‍🦱', '🧑‍🦳', '🫶'],
  moodPicker: [
    '😀',
    '😊',
    '🥰',
    '😌',
    '😐',
    '🤔',
    '🥺',
    '😢',
    '😭',
    '😠',
    '😡',
    '😱',
    '😴',
    '🥱',
  ],
  postComposer: ['🌍', '💪', '🍜', '🎨', '🐶', '🎵', '🎮', '✈️', '🏠', '❤️', '✨', '🔥'],
  dailyChallenges: ['💪', '🏃', '🧘', '🍎', '☕', '🎨', '🎮', '📸', '☀️', '🌧️'],
  socialActions: ['👋', '🤝', '🫶', '🫂', '💌', '🔔', '🎁', '⭐'],
} as const;

export const safeUsageNotes = [
  'Avoid country flags, political symbols, and culturally sensitive icons for identity.',
  'Use neutral defaults and allow optional skin tone modifiers where applicable.',
  'Keep emoji-only UI: no labels in user-facing surfaces.',
  'Ensure minimum 44px touch targets for mobile.',
  'Use 🌍 plus activity emojis instead of nationality indicators.',
] as const;
